cache:
  paths:
    - .m2/repository
    
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

image: docker:stable

services:
  - docker:dind

stages:
  - build:dependencies
  - test
  - build
  
build:dependencies:
  image: maven:3-jdk-12-alpine
  stage: build:dependencies
  script:
    - apk add docker
    - usermod -a -G docker
    - dockerd
    - docker ps
    - apk add --no-cache git
    - git clone --depth 1 https://github.com/rozagerardo/angorasix.parent-pom.git parent-pom
    - mvn clean install -f ./parent-pom/pom.xml 
    - mvn dependency:resolve
  
test:unit:
  image: maven:3-jdk-12-alpine
  stage: test
  script:
    - mvn verify -B
  artifacts:
    paths:
      - target/*.jar
      
test:integration:
  image: maven:3-jdk-12-alpine
  stage: test
  script: "mvn verify -B -Pintegration"
      
docker:version-tag:
  only:
    - master
  image: maven:3-jdk-12-alpine
  stage: build
  script: 
    - apk add docker
    - usermod -a -G docker
    - dockerd
    - docker ps
    - mvn dockerfile:build dockerfile:push -Ddockerfile.username=geroza -Ddockerfile.password=$DOCKER_SECRET -B 
  dependencies:
    - test:unit
      
docker:latest-tag:
  only:
    - tags
    - release-candidate
  except:
    - branches
  image: maven:3-jdk-12-alpine
  stage: build
  script: 
    - apk add docker
    - usermod -a -G docker
    - dockerd
    - docker ps
    - mvn dockerfile:tag -Dproject.plugin.dockerfile.tag=latest -
    - mvn dockerfile:build dockerfile:tag dockerfile:push -Ddockerfile.username=geroza -Ddockerfile.password=$DOCKER_SECRET -B
  dependencies:
    - test:unit
