cache:
  paths:
    - .m2/repository
    
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

image: docker:stable

services:
  - docker:dind

stages:
  - build:dependencies
  - test
  - build
  
build:dependencies:
  except:
    - tags
  image: maven:3-jdk-12-alpine
  stage: build:dependencies
  script:
    - apk add git
    - git clone --depth 1 https://github.com/rozagerardo/angorasix.parent-pom.git parent-pom
    - mvn clean install -f ./parent-pom/pom.xml 
    - mvn dependency:resolve
      
test:unit-integration:
  except:
    - tags
  image: maven:3-jdk-12-alpine
  stage: test
  script: "mvn verify -B -Pintegration"
  artifacts:
    paths:
      - target/*.jar
      
docker:version-tag:
  only:
    - master
  stage: build
  script: 
    - docker run --rm -v "$PWD":/usr/src/mymaven -v /var/run/docker.sock:/var/run/docker.sock -v "$CI_PROJECT_DIR/.m2":/root/.m2 -v "$PWD/target:/usr/src/mymaven/target" -w /usr/src/mymaven -e DOCKER_SECRET=$DOCKER_SECRET -e DOCKER_USER=$DOCKER_USER maven:3-jdk-12-alpine mvn -Ddocker dockerfile:build dockerfile:tag dockerfile:push  -s ./settings.xml -B
  dependencies:
    - test:unit-integration
      
docker:latest-tag:
  only:
    - /^latest-/
  except:
    - branches
  stage: build
  script: 
    - docker run --rm -v "$PWD":/usr/src/mymaven -v /var/run/docker.sock:/var/run/docker.sock -v "$CI_PROJECT_DIR/.m2":/root/.m2 -v "$PWD/target:/usr/src/mymaven/target" -w /usr/src/mymaven -e DOCKER_SECRET=$DOCKER_SECRET -e DOCKER_USER=$DOCKER_USER maven:3-jdk-12-alpine mvn -Ddocker=latest dockerfile:build dockerfile:tag dockerfile:push  -s ./settings.xml -B
  dependencies:
    - test:unit-integration
    
