image: docker:stable

services:
  - docker:dind

stages:
  - build:parent
  - test
  - build
  
before_script:
  
  
build:parent:
  image: maven:3-jdk-12-alpine
  stage: build:parent
  script:
    - apk add --no-cache git
    - git clone --depth 1 https://github.com/rozagerardo/angorasix.parent-pom.git parent-pom
    - mvn clean install -f ./parent-pom/pom.xml 
  artifacts:
    paths:
      - ~/.m2
  
test:unit:
  image: maven:3-jdk-12-alpine
  stage: test
  script:
    - mvn verify -B
  dependencies:
    - build:parent
  artifacts:
    paths:
      - target/*.jar
      
test:integration:
  image: maven:3-jdk-12-alpine
  stage: test
  script: "mvn verify -B -Pintegration"
  dependencies:
    - build:parent
      
docker:version-tag:
  only:
    - master
  image: maven:3-jdk-12-alpine
  stage: build
  script: 
    - apk add docker
    - docker ps
    - dockerd
    - docker ps
    - usermod -a -G docker
    - docker ps
    - service docker start
    - docker ps
    - sudo service docker start
    - docker ps
    - mvn dockerfile:build dockerfile:push -Ddockerfile.username=geroza -Ddockerfile.password=$DOCKER_SECRET -B 
  dependencies:
    - test:unit
      
docker:latest-tag:
  only:
    - tags
    - release-candidate
  except:
    - branches
  image: maven:3-jdk-12-alpine
  stage: build
  script: 
    - dockerd
    - mvn dockerfile:tag -Dproject.plugin.dockerfile.tag=latest -
    - mvn dockerfile:build dockerfile:tag dockerfile:push -Ddockerfile.username=geroza -Ddockerfile.password=$DOCKER_SECRET -B
  dependencies:
    - test:unit
