server:
  port: ${PORT:8085}

spring:
  application:
    name: ${APP_NAME:projects.contributors-presentation}
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://127.0.0.1:8761/eureka/}
