context:
  initializer:
    classes: com.angorasix.projects.presentation.BeansInitializer
server:
  port: ${A6_PROJECTS_PRESENTATIONS_PORT:9083}

spring:
  config:
    import: classpath:/api.yml, classpath:/security.yml
  application:
    name: ${A6_PROJECTS_PRESENTATIONS_APP_NAME:projects.presentation}
  data:
    mongodb:
      uri: ${A6_PROJECTS_PRESENTATIONS_MONGO_DB_URI:mongodb://localhost:27017/a6-projectpresentations}
