name: Workflow executed when pushing git tag for a new version

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-test-artifact:
    uses: AngoraSix/infra/.github/workflows/action-build-test-maven.yml@main
  publish-docker-image:
    needs: build-test-artifact
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: AngoraSix/infra/.github/workflows/action-push-gcp-maven.yml@main
    with:
      app: projects.presentations
    secrets:
      wif-provider: ${{ secrets.WIF_PROVIDER }}
      wif-service-account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - uses: actions/download-artifact@master
#      with:
#        name: Package
#        path: staging
#    - run: mkdir target && cp staging target
#    - uses: AngoraSix/infra/.github/workflows/action-push-gcp.yml@main
#      with:
#        app: projects-core
#      secrets:
#        wif-provider: ${{ secrets.WIF_PROVIDER }}
#        wif-service-account: ${{ secrets.WIF_SERVICE_ACCOUNT }}